language: rust
rust:
- stable
os:
- windows
jobs:
  include:
  - script: cargo test --verbose
  - script: cargo build --verbose --release
  - stage: GitHub Release
    script: echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      api_key:
        secure: qGGWqEyn60+PWH+oAwnHF1piwPEMw5zO/EsmNIEfzphzeskhdnCFNkYvhX7agzAYSX2eSByhmBgKf5pZkkfHga6t8aKQlB/XQqu1/EryNh/OwMFWsQidT4xEXm/L7dM/vy8iCh81yY6L/4CubDmpl6lqXGdi9EadBscBZVy4+lWU70zzK4jPb+YnFnQ8sg0/TqNg2v0RnO1s1J7jXh4vtfkpuzAACe2AmemewHBj8jWB1xDeYpjMq9i+qPG7PWoM7G1tBxnHU1pl2zCJ7tvX+wAFphdZuXWxFAHcvxrbRXWopBA6RgwezaAdcaxsQJb5hjiOlJWm33sHQZU1EdpZU+jtkW99hU0MZB5N5lrs1RrkGXY8dRBFlgz+41bN43e0e/6fuPq3iomemb3spDUz7eSQSgXvedmAIB3sXGB+abpciQanzWsF6B6c2PkVRXqfcS8xJugqKsSFtioohQZ4dlh78vR5qSatPIBzAa+gFZOKkwmlLB0C2Jye2r/qzvETdwVgY+3U/ZMDW0hoG29DTXWMiwndeb82rA1y76oRdA9d8/EHRasOhyqZus89oQjf7BRxWrcHjazp4W+dXjDCEXxmZn/y5guX0y6Ju2ORgA/fnSmBPpAJ+yuA+6xqF9k9yIkkyTVseki4cTHS8NSPMxm0L1gLArjuKrZQL+35JA0=
      skip_cleanup: true
      on:
        tags: true
env:
  global:
    secure: r+GZn1UP4CdLoEXWhkb7XFwFLEtOl7o6en2x9VukzPS1UN9ED0IoMTelzZm6U1PH6tGeNg/KR0vtG41tX/zmh4dl3f4B5J7xzF74yEqy66KherSNLMgjQWAyz1kX6rBIR9SsfUjACe3/LuG/2HNAXSuYaUyhe38vsFQXOZUWYcpV/NwhUgj4xkB+yYOz2e/5cUdYR3VJOETE6ufxYKVSNgHL2TbixmpKY2eeI0qI4xdspk22GF5BLgiWM+Tocw9gvR3lzGoJVgISmlflPw4ZwRlC+pJSag7zDyIFrOcSDqvDH6rYPDl7eN7pyuUkBsP41j5qouaR9ncODuh66br3DlA9Ajt4uQGeYQHvTA91w5o5tjqwtR6hb4/oA5h/PUGcj0NOeA3zsSo1+OD87Ho6fQ+nctBSSyes6tr7j7dDshqPPTWp7veHORN7BNXDU6Q/jHJkwRcWSt7aqa1700GE2Qa3+Utfqqa+a1e13KkKxiDHCcKhVBbZQmuZRcji6DFtmwh6h2Yl8+xMP3Q26pWZ37hgIuejqTRmtw0YaYHcbn7ioLjCVx7fCTPbQMOW0cOK1TirS5k2SWDxmVm3BoD1nluXjhgoz0dHMRdfoKHOgS1/dzJggRVnqONBqWNC71Bjuj3OSBznRZT7mdDYY/g3YeaDIr0GrSM85Z/rBT9ZjJc=
