language: rust
rust:
- stable
os:
  - osx
  - windows
  - linux
script:
  - cargo test --verbose
  - cargo build --verbose --release
env:
  global:
    secure: r+GZn1UP4CdLoEXWhkb7XFwFLEtOl7o6en2x9VukzPS1UN9ED0IoMTelzZm6U1PH6tGeNg/KR0vtG41tX/zmh4dl3f4B5J7xzF74yEqy66KherSNLMgjQWAyz1kX6rBIR9SsfUjACe3/LuG/2HNAXSuYaUyhe38vsFQXOZUWYcpV/NwhUgj4xkB+yYOz2e/5cUdYR3VJOETE6ufxYKVSNgHL2TbixmpKY2eeI0qI4xdspk22GF5BLgiWM+Tocw9gvR3lzGoJVgISmlflPw4ZwRlC+pJSag7zDyIFrOcSDqvDH6rYPDl7eN7pyuUkBsP41j5qouaR9ncODuh66br3DlA9Ajt4uQGeYQHvTA91w5o5tjqwtR6hb4/oA5h/PUGcj0NOeA3zsSo1+OD87Ho6fQ+nctBSSyes6tr7j7dDshqPPTWp7veHORN7BNXDU6Q/jHJkwRcWSt7aqa1700GE2Qa3+Utfqqa+a1e13KkKxiDHCcKhVBbZQmuZRcji6DFtmwh6h2Yl8+xMP3Q26pWZ37hgIuejqTRmtw0YaYHcbn7ioLjCVx7fCTPbQMOW0cOK1TirS5k2SWDxmVm3BoD1nluXjhgoz0dHMRdfoKHOgS1/dzJggRVnqONBqWNC71Bjuj3OSBznRZT7mdDYY/g3YeaDIr0GrSM85Z/rBT9ZjJc=
